# Generated by Django 4.2.5 on 2023-09-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passwords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Password"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("website", models.URLField(verbose_name="URL")),
                ("login", models.CharField(max_length=100, verbose_name="Login")),
            ],
        ),
    ]
