# Generated by Django 4.2.5 on 2023-09-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generator", "0004_alter_passwords_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwords",
            name="password",
            field=models.CharField(max_length=16, verbose_name="Password"),
        ),
    ]
